# docker-compose.yml
services:
  lilith_back:
    image: lilith_back
    container_name: lilith_back
    restart: always
    networks:
      - interservices

networks:
  interservices:
    external: true
