###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query {
  games {
    id
    name
  }
}


#####
subscription {
  subTogames {
    id
    name
  }
}

### header
{
  "Authorization": "Bearer {{token}}"
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

mutation {  
  createGame(
    dto: {
      name: "test"
    }
  ) {
    id
    name
    voting
    author_id
    author {
      id
      code
    }
    members
    members_obj {
      id
      code
    }
    items {
      id
      name
      author_id
      author {
        id
        code
      }
      state
      votes {
        id
        author_id
        author {
          id
          code
        }
        vote
      }
    }
  }
}


###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query {  
  game(
    dto: {
      game_id: "66c46756158599b6f305097d"
    }
  ) {
    id
    name
    voting
    author_id
    author {
      id
      code
    }
    members
    members_obj {
      id
      code
    }
    items {
      id
      name
      author_id
      author {
        id
        code
      }
      state
      votes {
        id
        author_id
        author {
          id
          code
        }
        vote
      }
    }
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

mutation {  
  joinGame(
    dto: {
      game_id: "66c463d568a181bf4fec74f0"
    }
  )
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

mutation {  
  leave_game(
    dto: {
      game_id: "66c46756158599b6f305097d"
    }
  )
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

mutation {  
  reveal(
    dto: {
      sessionId: "65265be7b639d18e44b072c2"
      itemId: "65265c22b639d18e44b072c3"
    }
  )
}