###
POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer token
X-REQUEST-TYPE: GraphQL

query {
  sessions {
    id
    name
  }
}


#####
subscription {
  subToSessions {
    id
    name
  }
}

### header
{
  "Authorization": "Bearer token"
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer token
X-REQUEST-TYPE: GraphQL

mutation {  
  createSession(
    dto: {
      name: "test2"
    }
  ) {
    id
    name
    voting
    members
    items {
      id
      name
      author
      state
      votes {
        id
        member
        vote
      }
    }
  }
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer token
X-REQUEST-TYPE: GraphQL

mutation {  
  joinSession(
    dto: {
      sessionId: "65265be7b639d18e44b072c2",
      username: "fabrice"
    }
  )
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer token
X-REQUEST-TYPE: GraphQL

mutation {  
  createItem(
    dto: {
      sessionId: "65265be7b639d18e44b072c2",
      author: "fabrice",
      name: "Synchro AD des groupes"
    }
  ) {
    id
    name
    author
    state
    votes {
      id
      member
      vote
    }
  }
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer token
X-REQUEST-TYPE: GraphQL

mutation {  
  createVote(
    dto: {
      sessionId: "65265be7b639d18e44b072c2"
      itemId: "65265c22b639d18e44b072c3"
      member: "fabrice"
      vote: "XL"
    }
  ) {
    id
    member
    vote
  }
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer token
X-REQUEST-TYPE: GraphQL

mutation {  
  removeVote(
    dto: {
      sessionId: "65265be7b639d18e44b072c2"
      itemId: "65265c22b639d18e44b072c3"
      voteId: "65265ccab639d18e44b072c4"
    }
  )
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer token
X-REQUEST-TYPE: GraphQL

query {  
  session(
    dto: {
      sessionId: "65bbc7217d8c815ca2c7d120"
    }
  ) {
    id
    name
    voting
    members
    items {
      id
      name
      author
      state
      votes {
        id
        member
        vote
      }
    }
  }
}

###
POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer token
X-REQUEST-TYPE: GraphQL

mutation {  
  reveal(
    dto: {
      sessionId: "65265be7b639d18e44b072c2"
      itemId: "65265c22b639d18e44b072c3"
    }
  )
}